[package]
name = "bevy_debug_menu"
version = "0.1.0"
authors = ["Brice DAVIER <bricedavier@gmail.com>"]
edition = "2018"

[dependencies]
bevy = "0.4.0"
ron = "0.6.4"
serde = "1.0"
interpolation = "0.2.0"